services:
  dockerized-php-xdebug: #name of the docker service
    build: #tells Docker Compose to build a Docker image for this service.
      context: . #means the build context is the current directory (where the docker-compose.yml is located).
      dockerfile: Dockerfile.dev #specifies to use the Dockerfile.dev file 
    ports:
      - 8086:80 #Maps port 8086 on your host machine to port 80 inside the container.
    volumes:
      - "./src/:/var/www/html" #Mounts the host folder ./src/ (relative to your docker-compose.yml file) into /var/www/html inside the container. This allows you to edit code on your host machine and have the changes immediately reflected 
#inside the container without rebuilding.